### ISSUE TITLE
sample: multi-line strings should be balanced

### ISSUE THREAD

**Issue by zimbatm** [nix-community/nixpkgs-fmt#109]
The multi-line string should behave more like the list `[` and `]`

## Input
```nix
{
  string =          ''
hello
'';
  list = [
hello
];
}
```

## Output
```nix
{
  string = ''
    hello
    '';
  list = [
    hello
  ];
}

```

## Desired output

```nix
{
  string = ''
    hello
  '';
  list = [
    hello
  ];
}
```

**Comment by zimbatm** [comment]
What do you think @matklad ?

**Comment by matklad** [comment]
I think this makes sense, yeah.

what if the string itself is indented? Should it be

```rust
''
hello
''
```

or 

```rust
''
  hello
''
```

?

**Comment by zimbatm** [comment]
I guess
```nix
''
  hello
''
```
Since lists are indented like:
```nix
[
  hello
]
```

The only part where list-like feature doesn't work is on a single line since `[ hello ]` is okay but `'' hello ''` would add two new whitespaces around to the text output.
