### ISSUE TITLE
default.nix

### ISSUE THREAD

**Issue by domenkozar** [nix-community/nixpkgs-fmt#113]
I'd love to use it if I can `nix-build` :)

**Comment by zimbatm** [comment]
soon :) I don't want to mess with carnix or update the cargoSha256 every time Cargo.lock changes

**Comment by domenkozar** [comment]
Can be IFD.

**Comment by zimbatm** [comment]
Got any examples?

**Comment by domenkozar** [comment]
I never did any Rust so I don't know the tooling, but that's what haskell tooling avoids by using IFD.

**Comment by zimbatm** [comment]
there you go @domenkozar :)

**Comment by domenkozar** [comment]
<3
