### ISSUE TITLE
remove line break after expanded let ... in

### ISSUE THREAD

**Issue by layus** [nix-community/nixpkgs-fmt#125]
```nix
# One line, everyone's happy
let self = { }; in self
```

https://github.com/nix-community/nixpkgs-fmt/issues/65#issuecomment-507306029 suggests that we could consider `let ... in` just as an `assert ...;` or a `with ... ;` statement that does not indent the following body. In that case example 2 is inconsistent.

```nix
# input
# This should be okay if `let` is considered like a `with` or `assert` 
let self = { }; in
self
```

```nix
# nix-fmt output
# But it is expanded :-(
let
  self = {};
in
self
```

Overall, it seems that the `let ... in body` is expanded (split across multiple lines as long as it is not written on one line. I think that expanding the `let ... in` part should be independent from expanding the body itself and from decoupling the `in` from the body.

The above example is made even worse by the fact that we do not indent toplevel let bodies (https://github.com/nix-community/nixpkgs-fmt/pull/108). The `self` really looks weird and could be on the same line as the `in`.

May I propose the following patterns ?

```nix
let foo = bar; in foo
```
```nix
let foo = bar; in
foo
```
```nix
let
  foo = bar;
in {
  bar = foo;
}
```

The implicit rule is that when the let+in construct is one one line, it behaves like a `with` or `assert`, and when it is on several lines (expanded form), no line break is enforced after the `in` (which means that line breaks are only enforced for a multi-line body after a single line let+in).

**Comment by Rizary** [comment]
@layus I try in nixpkgs-fmt website the following code:
```
{foo,bar}:
let foo = let x = y; in 
z; 
in
body
```

And I get

```
{ foo, bar }:
let
  foo = let
    x = y;
  in
    z;
in
body
```

Based on your proposal, what the code should look like? If we want one line `let` not expanded, then I think it well be transformed into:
```
{ foo, bar }:
let foo = 
  let x = y;
  in
    z;
in
body
```

Is it correct?

between

**Comment by layus** [comment]
I would describe the rules as is:
1. if the `let` and the corresponding `in` are in the same line, this is a single-line let-intro.
2. if the whole let body stands on a single line, and on the same line as the `in` keyword, then it is a single line let-body.
Otherwise, we have respectively multiline let-intros, and multiline let-bodies.
In that case, indent them as ususal.

```nix
{foo,bar}:
let foo = let x = y; in 
z; 
in
body
```

becomes

```nix
{foo,bar}:
let
  foo = let x = y; in 
    z;
in
body
```

So we agree on the let-body rules, but not on the let-intro.

**Comment by Rizary** [comment]
Please give the above PR a try.

**Comment by Rizary** [comment]
I reopen this issue for another PR. Currently, the fmt produce the following output:
```
{ foo, bar }:
let
  foo = let x = y; in
    z;
  #all in one line
  bar = let x = 3; in x;
  bax = listToAttrs (
    map
      (
        v: let n = v.where; in
          functionA "${n}.automount" (functionB n v)
      ) cfg.fooA
  );
in
{
  inherit foo bar;
  baz = 3;
}

```

Meanwhile, from my understanding, we want to achieve something like
```
{ foo, bar }:
let
  foo = let x = y; in
    z;
  #all in one line
  bar = let x = 3; in x;
  bax = listToAttrs (map
          (v: let n = v.where; in 
             functionA "${n}.automount" (functionB n v)) cfg.fooA);
in {
  inherit foo bar;
  baz = 3;
}
```

Is the above correct?

Note: if between `let ... in` exists linebreak, the `let` would be expanded.

**Comment by layus** [comment]
There is a bit much in your example to understand exactly what I/we should focus on.

The main difference between your snippets is that you reduced the vertical span of some constructs. This is something that I have not yet completely understood. I have some ideas to further reflection on that, but I think there is already a tracking issue for that.

The removed line break after the last `in`falls in the same kind of concern for me.

Is that right ?

**Comment by Rizary** [comment]
@layus Agreed. Sorry about the above code. I think my focus here should only be about  `let ... in`.
