### ISSUE TITLE
sample: normalize indentation to tabs or spaces

### ISSUE THREAD

**Issue by efx** [nix-community/nixpkgs-fmt#131]
## Input
```nix
let
  pkgs = ((import (fetchTarball https://github.com/NixOS/nixpkgs/archive/staging.tar.gz))  {});
in
pkgs.buildEnv {
  name = "innovu-httpd";
  paths = [ pkgs.apacheHttpd pkgs.modsecurity_standalone ];
  postBuild = ''
    # no tabs
		# tabs
  '';
}

```

## Output
```nix
let
  pkgs = ((import (fetchTarball https://github.com/NixOS/nixpkgs/archive/staging.tar.gz)) {});
in
pkgs.buildEnv {
  name = "innovu-httpd";
  paths = [ pkgs.apacheHttpd pkgs.modsecurity_standalone ];
  postBuild = ''
        # no tabs
    		# tabs
  '';
}

```

## Desired output
Ideally the output should confirm to whatever the nix language specifies or the conventions of nixpkgs. I don't really care whether it is tabs or spaces. The below uses spaces just to show the indentation consistency in GitHub's markdown code block:
```nix
let
  pkgs = ((import (fetchTarball https://github.com/NixOS/nixpkgs/archive/staging.tar.gz))  {});
in
pkgs.buildEnv {
  name = "innovu-httpd";
  paths = [ pkgs.apacheHttpd pkgs.modsecurity_standalone ];
  postBuild = ''
    # no tabs
    # tabs
  '';
}

```

**Comment by zimbatm** [comment]
good point. Do you have any idea to find out the size of the tabs that the user used?

**Comment by matklad** [comment]
Yeah, we currently don't handle tabs at all, and just hard-code two-spaces indentation. I don't know what's the right solution here. The common wisdom is "use spaces", so we can just force-convert tabs to spaces. However, I've recently heard compelling argument to use tabs: it helps accessibility, because people with poor eyesight often want to configure tab size to unusual values.

**Comment by zimbatm** [comment]
Then we would still have the same problem but in reverse :)

The nix code in nixpkgs is formatted with 2 spaces and that acts as our canonical representation of code.

**Comment by zimbatm** [comment]
The current coding convention for nixpkgs is encoded over here: https://nixos.org/nixpkgs/manual/#sec-syntax

The goal of nixpkgs-fmt is to be adopted as a tool to format nixpkgs. Until that happens the format should stay largely the same as what is being used in nixpkgs.
