### ISSUE TITLE
Scientific notation is corrupted

### ISSUE THREAD

**Issue by ocharles** [nix-community/nixpkgs-fmt#150]
**Describe the bug**
`nixpkgs-fmt` changes the meaning of scientific notation.

**To Reproduce**

Format the following expression:

```nix
3.9e-3
```

It will format this as

```nix
3.9 e-3
```

which is not the same expression.

**Expected behavior**

The file is unchanged

**System information**

* `nixpkgs-fmt --version`

nixpkgs-fmt 0.6.0

**Additional context**

**Comment by Mic92** [comment]
Interestingly it only supports it for floating point (`1.0e1` is valid, but not `1e1`)
