### ISSUE TITLE
sample: function body indent

### ISSUE THREAD

**Issue by zimbatm** [nix-community/nixpkgs-fmt#151]
I think the function body shouldn't be indented if the arguments are on the same level.

## Input
```nix
let
  aaa =
 {foo,bar}:
              foo+bar
;
bbb = {foo,bar}:
              foo+bar
;
in
  null
```

## Output
```nix
let
  aaa =
    { foo, bar }:
      foo + bar
  ;
  bbb = { foo, bar }:
    foo + bar
  ;
in
null

```

## Desired output

```nix
let
  aaa =
    { foo, bar }:
    foo + bar
    ;
  bbb = { foo, bar }:
    foo + bar
    ;
in
null
```

**Comment by wmertens** [comment]
Here you propose two rules: if the function signature (sorry I don't know the proper name) is on the same line as a key, keep it there. Else indent it. In either case, don't indent the body.

I would like an additional rule: if the whole function fits on one line, do it:

```nix
let
  aaa = { foo, bar }: foo + bar;
  bbb = { foo, bar }: foo + bar;
in
null
```

And one more rule: I would prefer that function signatures are in predictable places (makes for easier reading), so I'd propose that a signature always goes on the same line as the attribute key, except if that makes the line too long. I'd prefer there to be no choice for this. Then you get these styles:

```nix
let
  aaa = { foo, bar }: foo + bar;
  bbb = { foo, bar }: {
    meep = foo + bar;
    boop = bar + foo;
  };
  bbb =
    { foo, bar, suchALongNameOhWowThatsReallyLong }: {
      meep = foo + bar;
      boop = bar + foo;
    };
  ccc =
    { foo
    , bar
    , suchALongNameOhWowThatsReallyLong
    }: null;
in
null
```

The `ccc` shows an expanded signature, I believe this is how it's formatted even though I'm more a fan of 
```nix
{
  ccc =
    {
      foo,
      bar,
      suchALongNameOhWowThatsReallyLong
    }: null;
}
```

**Comment by zimbatm** [comment]
thanks. I need to take some focused time to fix this, this is the main remaining issue with nixpkgs-fmt in my opinion.
