### ISSUE TITLE
sample: multi-line antiquotations appears to reset indentation

### ISSUE THREAD

**Issue by rycee** [nix-community/nixpkgs-fmt#166]
## Input
```nix
''
  foo
  ${
    foo
  }
  foo
''
```

## Output
```nix
''
  foo
  ${
foo
}
  foo
''

```

## Desired output

```nix
''
  foo
  ${
    foo
  }
  foo
''
```
(same as input)

**Comment by layus** [comment]
It seems it would be trivial to fix by adding NODE_STRING_INTERPOL ([interpol](https://www.interpol.int/) ?) to the list of anchors. But that gives 

```diff
diff --git a/lib/asserts.nix b/lib/asserts.nix
index 8a5f1fb3feb..a151e1f178f 100644
--- a/lib/asserts.nix
+++ b/lib/asserts.nix
@@ -38,7 +38,7 @@ rec {
   assertOneOf = name: val: xs: assertMsg
     (lib.elem val xs)
     "${name} must be one of ${
-      lib.generators.toPretty {} xs}, but is: ${
-        lib.generators.toPretty {} val}";
+                            lib.generators.toPretty {} xs}, but is: ${
+                                                                    lib.generators.toPretty {} val}";
 
 }
```

Not what people expect I guess.

We can simply indent it like lists, but you get very weird unindented results, as the indent appears to be counted from the indent of then enclosing `''`.

```rust
         .rule("Indent antiquotation content")
            .inside(NODE_STRING_INTERPOL)
            .not_matching([TOKEN_INTERPOL_START, TOKEN_INTERPOL_END])
            .set(Indent)
```

```nix
Before:
    ''
      foo bar ${if test then
                                "me"
                    else
    "you"
+ " !"
                }
    ''

After:
''
  foo bar ${if test then
  "me"
else
  "you"
  + " !"
}
''
```

May I suggest that, from what I have seen, one usually expects the indent level to be incremented from the start of the enclosing line of text ?

```nix
''
  foo bar ${if test then
      "me"
    else
      "you"
      + " !"
    }
''
```

I have no idea how to do that at the moment, but wanted to share thoughts.

**Comment by layus** [comment]
There are other examples of antiquot where the aligment is on the begining of the line, like this:

```nix
''
  foo bar ${if test then
    "me"
  else
    "you"
    + " !"
  }
''
```

**Comment by zimbatm** [comment]
Maybe we should just leave the code alone if it's part of a string interpolation

**Comment by layus** [comment]
Do mean that you want to miss the opportunity to format this ? :smiling_imp:  (https://github.com/NixOS/nixpkgs/blob/master/nixos/lib/make-options-doc/default.nix#L93-L130)

```nix
  # TODO: declarations: link to github
  singleAsciiDoc = name: value: ''
    == ${name}
    ${value.description}
    [discrete]
    === details
    Type:: ${value.type}
    ${ if lib.hasAttr "default" value
       then ''
        Default::
        +
        ----
        ${builtins.toJSON value.default}
        ----
      ''
      else "No Default:: {blank}"
    }
    ${ if value.readOnly
       then "Read Only:: {blank}"
      else ""
    }
    ${ if lib.hasAttr "example" value
       then ''
        Example::
        +
        ----
        ${builtins.toJSON value.example}
        ----
      ''
      else "No Example:: {blank}"
    }
  '';

in {
  inherit optionsNix;
```

Leaving it alone is always an option, but I see that there is already quite a bit of logic to handle indented strings. I guess it is more a matter of finding the bug than implementing everything from scratch.

**Comment by zimbatm** [comment]
That's my worry; how much logic will we need to handle string interpolation? I might be mistaken but a human might take the actual surrounding string as a hint for formatting interpolation. This might make it impossible to find a simple rule-set that applies nicely.

Unless there is a really simple fix, I think we should first get all of the rest formatting nicely, and then come back to the string interpolations and see if we have some complexity budget left over.

**Comment by layus** [comment]
Got a second chance to think about this one.

We cannot move `${` because adding spaces before changes the string.
We cannot anchor the antiquotation body to `${` because it fails (see [above](https://github.com/nix-community/nixpkgs-fmt/issues/166#issuecomment-583894243))

As a first approximation, we could leave the antiquotation body as-is, but in this case we need to re-indent it with the indented string lines. In this case we trust the authors with the indent and alignment of these pieces of code.

My idea is that we could trust users with the placement of the first node inside the antiquotation, and use that as an anchor for the remaining of the body.
Not sure if it works in all the cases, and some tuning will be needed (for exemple, set minimum indent to be at least the indented string indent.

Another option is to use the indent of the first node on the second line, if such a line exists.

**Comment by Rizary** [comment]
This is my current test case:
```
{
  foo = ''
    bar = ${builtins.concatStringsSep " " [
    1
    2
    3
  ]}
     bla = hoi
  '';

  bar = ''
      foo
    ${
    foo
    }
         foo
  '';

  baz =
    ''
      foo
       ${
      foo
      }
      foo
    '';

  foo =
    ''
      bar = ${builtins.concatStringsSep " " [
      1
      2
      3
    ]}
       bla = hoi
    '';
}
```

it still fails, because the current anchor is `NODE_KEY_VALUE` and the lowest indent level of the `${` is like the above, I am not sure if I can make it below 0.

**Comment by layus** [comment]
Yes, nested antiquotations ;)

**Comment by Rizary** [comment]
After trying for awhile, this happened because of https://github.com/nix-community/rnix-parser/issues/16 and how `NODE_STRING` is formatted.

I'll try to work on rnix first and come to this soon.
