### ISSUE TITLE
What about empty lines ?

### ISSUE THREAD

**Issue by layus** [nix-community/nixpkgs-fmt#170]
Maybe we should allow empty lines inside the let and around the in keywords.
The following diff removes empty lines that look fine to me.

I have no strong opinion, but are there already a formal decision in nixpkgs-fmt about this ?

## Diff

https://gist.github.com/layus/de240e98ca4872e5800111913414a984

**Comment by Rizary** [comment]
I was thinking about the multiple line break after `let` and `in` before. But in my understandig, the goal of nixpkgs-fmt is to assist `nixpkgs` repository which one of the go-to place for beginner user to learn about nix syntax and try to contribute back into the repository.

The problem with allowing multiple line in my point of view is that it will not help maintainer which like current `let ... in` syntax but forgot to delete the additional linebreak, or beginner nix user who experienced similar case with their code.

I realized that we are trying to give `nixpkgs-fmt` user as much freedom as they want to their own nix style, but I think we give too much freedom if the additional linebreak is allowed (I know it seems silly to abuse linebreak multiple times after `let` or `in`).

I am open to this actually, but I like the current `nixpkgs-fmt` result regarding empty lines after `let` and `in`.

**Comment by layus** [comment]
Makes sense to me :-)
