### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by lovesegfault** [nix-community/nixpkgs-fmt#171]
The current release is missing some nice fixes.

**Comment by Rizary** [comment]
@lovesegfault Hi! thank you for opening the issue.

I try to reload the page several times but can only see one sentence in this issue. I wonder if my network/computer has the issue, but apparently it is not.

Would you mind to re-post/reexplain about the nice fixes that missing from the previous release than the current? It would be helpful for us to find and fixed it without rollback to the previous release.

**Comment by lovesegfault** [comment]
@Rizary It really is just one sentence, I'd just like to pick up these changes: https://github.com/nix-community/nixpkgs-fmt/compare/v0.6.1...master

In particular #125 #168 #169

**Comment by Rizary** [comment]
@lovesegfault Good to hear that! Ah, would you also mind to elaborate more example on each PR that consist of bug? Did it broke your  `.nix` code format badly? I am sure that we cannot adhere everyone's nix style formatting, but if it looks pretty bad (which is never exist in nixpkgs' repository) then that is a problem and we need to fix it soon.

**Comment by lovesegfault** [comment]
I'm just asking for there to be a new release so that `nixpkgs-fmt` stops adding a line break after my `let ... in` clauses, as per #125. This was fixed in master but not released yet.

**Comment by Rizary** [comment]
We have the new release. Enjoy!!
https://github.com/nix-community/nixpkgs-fmt/releases/tag/v0.7.0

**Comment by lovesegfault** [comment]
Thank you!!
