### ISSUE TITLE
Inconsistent indentation for comment line after let…in

### ISSUE THREAD

**Issue by emilazy** [nix-community/nixpkgs-fmt#179]
## Input
```nix
let
  x = 123;
in
# foo
x
```

## Output
```nix
let
  x = 123;
in
  # foo
x
```

## Desired output

The original, or at least consistently indenting the `x` as well. All the bugs I could find for this were marked as resolved.

**Comment by zimbatm** [comment]
agreed, comments should always align with the next line's indent

**Comment by Rizary** [comment]
hi, please refer to #180, In my test, comment in the top level node let should be fixed now
