### ISSUE TITLE
sample: indented `with`

### ISSUE THREAD

**Issue by zimbatm** [nix-community/nixpkgs-fmt#189]
## Input
```nix
let
  pkgs = import <nixpkgs> {};
in
with pkgs;
mkShell {}
```

## Output
```nix
let
  pkgs = import <nixpkgs> { };
in
  with pkgs;
  mkShell { }

```

## Desired output

```nix
let
  pkgs = import <nixpkgs> { };
in
with pkgs;
mkShell { }

```

**Comment by timokau** [comment]
I'm not sure how much bikeshedding is desired here. Feel free to ignore, I don't feel incredibly strongly about this. I'd personally prefer either

```nix
let
  pkgs = import <nixpkgs> { };
in
  with pkgs; mkShell { }
```

or

```nix
let
  pkgs = import <nixpkgs> { };
in with pkgs; mkShell { }
```

with slight preference to the first version.

**Comment by zimbatm** [comment]
Noted @timokau.

One thing we are going to change is that `let <header> in <body>`, the body won't be indented anymore. This is to avoid massive re-indents when a `let .. in` is being introduced in an existing code-base.

**Comment by timokau** [comment]
I really dislike the way that looks, if you're talking about the following style:

```nix
let
  pkgs = import <nixpkgs> { };
in
with pkgs;
mkShell { }
```

Despite that, it makes it somewhat hard to detect the scope of the "in". You can achieve the same result (no additional indentation) in 99% of the cases by just adding the thing the "let" applies to to the same line:

```nix
let
  pkgs = import <nixpkgs> { };
in with pkgs; mkShell {
  something;
}
```

has the same indentation as

```nix
mkShell {
  something;
}
```

Again though, any consistent formatting is better than the current state. Just offering my opinion.

**Comment by zimbatm** [comment]
Usually, the body is a bit longer. Not sure if that would affect your preference?

```nix
let
  pkgs = import <nixpkgs> {};
  # ...
in
with pkgs;
mkShell {
  buildInputs = [
    curl
    go
    bash
  ];
}
```

**Comment by timokau** [comment]
Not really, I'd still prefer

```nix
let
  pkgs = import <nixpkgs> {};
  # ...
in with pkgs; mkShell {
  buildInputs = [
    curl
    go
    bash
  ];
}
```

as it clearly delimits what the `in` is affecting (by indentation) while still not adding another indentation level.

**Comment by Rizary** [comment]
At first, what I was trying to do is to make developer more flexible in
structuring `let...in` so if they put a newline on the `in` body, it will
be aligned with the `in` value.

Later on, I put all the `in` body to always newline because I found it more
readable instead of having `in with foo; mkShell {... `. But I think it is
just my personal taste.

**Comment by aaronjanse** [comment]
Right now`let x = 1;` can all be on the same line iff written that way originally. Could the same apply to `in with pkgs; mkShell {` or at least `in {`?

**Comment by Rizary** [comment]
The idea would be, if user put `let` and `in` in the same line, then only `in` that will not get expanded.

**Comment by Rizary** [comment]
Currently, we decided to go with the desired output:
```
let
  pkgs = import <nixpkgs> { };
in
with pkgs;
mkShell { }
```

I think we will have broader opinion when we try to bring nixpkgs-fmt as default formatter of nixpkgs repository. 

So I'll close this as it is already output correctly.
