### ISSUE TITLE
sample: line collapses

### ISSUE THREAD

**Issue by zimbatm** [nix-community/nixpkgs-fmt#195]
For some reason the lines get collapsed:

## Input
```nix
let
  foo = 3;

  bar = 4;
in
foo + bar
```

## Output
```nix
let
  foo = 3;
  bar = 4;
in
foo + bar

```

## Desired output

see Input

**Comment by Rizary** [comment]
Isn't it intended behavior? I think I've seen similar case before and it
remove the extra newline.

**Comment by B4dM4n** [comment]
`v0.7.0` didn't remove such lines. This behavior was introduced with `v0.8.0`.

From the [Design decisions](https://github.com/nix-community/nixpkgs-fmt#design-decisions):

> 3. Respect the developer's expressivity. Empty lines can be useful as a way to separate blocks of code.



The line removal seems only to happen in let expressions, but not before comment lines. Sets keep their empty lines:

## Input

```nix
let
  foo = 1;


  # comment
  bar=2;
  # comment

  baz = 3;
in
{
  foo = 1;

  bar=2;
}
```

## Output
```nix
let
  foo = 1;


  # comment
  bar = 2;
  # comment
  baz = 3;
in
{
  foo = 1;

  bar = 2;
}
```

**Comment by Rizary** [comment]
@B4dM4n 

Yep, that's correct. I'm still investigating the problem.
