### ISSUE TITLE
Debug (?) output on stdout.

### ISSUE THREAD

**Issue by pbogdan** [nix-community/nixpkgs-fmt#201]
**Describe the bug**

Reformatting the code produces what looks like some sort of debugging output which is definitely not part of the input.

**To Reproduce**

1. Pipe a file onto stdin of `nixpkgs-fmt`.
2. Observe stdout contains lines like the following:
  ```
  node: NODE_STRING@[8934; 9139), indent: IndentLevel { level: 3, alignment: 0 }
  node: NODE_STRING@[9595; 9606), indent: IndentLevel { level: 3, alignment: 0 }
  node: NODE_STRING@[9648; 9659), indent: IndentLevel { level: 3, alignment: 0 }
  node: NODE_STRING@[13768; 13908), indent: IndentLevel { level: 5, alignment: 0 }
  node: NODE_STRING@[16687; 18048), indent: IndentLevel { level: 3, alignment: 0 }
  node: NODE_STRING@[18477; 18754), indent: IndentLevel { level: 3, alignment: 0 }
  node: NODE_STRING@[19488; 19658), indent: IndentLevel { level: 4, alignment: 0 }
  node: NODE_STRING@[19679; 19877), indent: IndentLevel { level: 3, alignment: 0 }
  node: NODE_STRING@[19930; 20145), indent: IndentLevel { level: 3, alignment: 0 }
  node: NODE_STRING@[20167; 20178), indent: IndentLevel { level: 3, alignment: 0 }
  node: NODE_STRING@[20201; 20212), indent: IndentLevel { level: 3, alignment: 0 }
  node: NODE_STRING@[20236; 20247), indent: IndentLevel { level: 3, alignment: 0 }
  node: NODE_STRING@[20631; 20758), indent: IndentLevel { level: 3, alignment: 0 }
  node: NODE_STRING@[22103; 22326), indent: IndentLevel { level: 2, alignment: 0 }
  ```

**Expected behavior**

Save for formatting changes the content of the file remains unchanged, any debug output is directed to stderr (and / or optionally suppressed).

**System information**

* `nixpkgs-fmt --version`

0.8.0

**Additional context**

N/A

**Comment by Rizary** [comment]
Hi,

Thank you. Yeah this shouldn't be happening.

I'll fix it soon.

**Comment by cole-h** [comment]
Hi, sorry to bother, but would it be possible to cut a new release with this patch present? As it stands now, using any auto-formatting mechanism litters the file with garbage like `node: NODE_STRING@[8934; 9139), indent: IndentLevel { level: 3, alignment: 0 }` from above. This renders `nixpkgs-fmt` pretty much unusable.

Sorry to be "that guy."

**Comment by Rizary** [comment]
We are planning to release the new version today.

I'm very sorry for the inconvenience.
