### ISSUE TITLE
sample: closing bracket on a new line

### ISSUE THREAD

**Issue by B4dM4n** [nix-community/nixpkgs-fmt#206]
Thanks for fixing #198 (and others), but I found another case a `)` is put on a new line instead of the same line as the preceding `}`.

## Input
```nix
fun "arg"
  (callPackage ./. {
    inherit foo;
  })

```

## Output
```nix
fun "arg"
  (callPackage ./. {
    inherit foo;
  }
  )

```

## Desired output

```nix
fun "arg"
  (callPackage ./. {
    inherit foo;
  })

```

**Comment by Rizary** [comment]
Thank you, I'll look into it.

**Comment by Rizary** [comment]
I tried this with `v1.0.0` and it's already fixed. I'm going to close the issue within today.

**Comment by B4dM4n** [comment]
You are right, the behavior is not present in `v1.0.0` anymore.

Thanks for your effort.
