### ISSUE TITLE
0 / 1 have been reformatted

### ISSUE THREAD

**Issue by colemickens** [nix-community/nixpkgs-fmt#215]
**Describe the bug**

```
> nixpkgs-fmt latest.nix
0 / 1 have been reformatted
```

Uh? Why?

**To Reproduce**
This is a valid nix file...

```
{ version = { name = "Firefox Nightly"; release = false; version = "80.0a1"; }; versionInfo = { chksum = "https://archive.mozilla.org/pub/firefox/nightly/2020/07/2020-07-06-21-50-07-mozilla-central/firefox-80.0a1.en-US.linux-x86_64.checksums"; chksumSig = "https://archive.mozilla.org/pub/firefox/nightly/2020/07/2020-07-06-21-50-07-mozilla-central/firefox-80.0a1.en-US.linux-x86_64.checksums.asc"; sha512 = "1c69922b01f732d493c292632a6664ba6e55c8f9f2760a369b4f4868bbaaba0cfebce5f30c5c2a6357fc54de42c22d6be0a882755f6a4007bd8eea98b7668de8"; url = "https://archive.mozilla.org/pub/firefox/nightly/2020/07/2020-07-06-21-50-07-mozilla-central/firefox-80.0a1.en-US.linux-x86_64.tar.bz2"; }; }
```

1. Run `nixpkgs-fmt latest.nix` on the above file
2. ...

**Expected behavior**
It to be formatted in place.

**System information**

* `nixpkgs-fmt --version` nixpkgs-fmt 0.9.0

**Additional context**

**Comment by Rizary** [comment]
Hi thank you for opening the issue.

Where did you get the nixpkgs-fmt? From the nixpkgs repository or from this
github?

**Comment by colemickens** [comment]
I got it from nixpkgs (nixos-unstable).

**Comment by zimbatm** [comment]
It's because nixpkgs-fmt doesn't enforce line-length limits and the file already respects all of the rules like spacing between elements. If you add a `\n` somewhere in the middle it will get reformatted.

**Comment by colemickens** [comment]
Oh interesting, thanks @zimbatm. This is a bit annoying in the use-case (`nix eval .#latestVersionInfo > ./info.nix; nixpkgs-fmt ./info.nix` where it's a bit awkward to do that workaround.

**Comment by colemickens** [comment]
(this isn't a huge issue, I was convinced to use `--json | jq` and `builtins.fromJSON` anyway)

**Comment by zimbatm** [comment]
agreed, in that case you might want to use a pretty-printer instead of a code formatter, which is quite close but not exactly the same.

**Comment by forgondolin** [comment]
I'm sorry commenting on this but I'm having a similar problem:
```
deployment.healthChecks = { 
      cmd = [{ 
              cmd = ["test \"$(systemctl is-active test.service | wc -l)\" -eq 1"];
```
when running `nixpkgs-fmt file.nix --check`:

_1 / 35 would have been reformatted
error: fail on changes_

Already tried a multi line string with  `'' test \"(systemctl.....)" '' `
but no success
