### ISSUE TITLE
Combine nixpkgs-fmt, rnix-lsp, and rnix-parser into a monorepo

### ISSUE THREAD

**Issue by Rizary** [nix-community/nixpkgs-fmt#221]
**Is your feature request related to a problem? Please describe.**
rnix-parser is heavily used by nixpkgs-fmt. So it will be nice if we include the parser into single repo with the formatter.
rnix-lsp can get benefit when using the formatter and the parser.

**Describe the solution you'd like**
Combining all the 3 repo into 1 can make maintenance easier, and create some powerful nix tooling in the future.

**Describe alternatives you've considered**
create 1 repo and add all 3 as a submodule (but it's not effective)

**Additional context**
maybe we can create rnix-analyzer with these 3 repo combined into one.

**Comment by Rizary** [comment]
Hi @jD91mZM2 ! sorry I forget to tag you for your opinion.

**Comment by jD91mZM2** [comment]
https://github.com/nix-community/rnix-parser/issues/3

**Comment by Rizary** [comment]
I think I've read this, it's already 1y ago. So it seems the decision still not changed. Noted on that.
