### ISSUE TITLE
sample: preserving `in {` when on same line

### ISSUE THREAD

**Issue by aaronjanse** [nix-community/nixpkgs-fmt#223]
## Input
```nix
let pkgs = "...";
in {
  foo = pkgs.htop;
}
```

## Output
```nix
let pkgs = "...";
in
{
  foo = pkgs.htop;
}

```

## Desired output

```nix
let pkgs = "...";
in {
  foo = pkgs.htop;
}
```

**Comment by Rizary** [comment]
I think this is by design to have a `{` in the new line. Although, we have previous discussion in #125 and our choice is to have `{` in the new line.

**Comment by aaronjanse** [comment]
Ah okay. I'll respect the decision made in that discussion :-)

By the way, thank you to the maintainers of this tool. It's saved me a lot of time.
