### ISSUE TITLE
No inner indentation inside multiline comments

### ISSUE THREAD

**Issue by AluisioASG** [nix-community/nixpkgs-fmt#243]
Multiline `/* */` comments are being aggressively reindented, to the point of losing any inner indentation. Examples were taken from https://github.com/NixOS/nixpkgs/blob/e1ff5c3d8c4ca7101f2c820f85d8290303deaa53/lib/strings.nix#L178-L185 and https://github.com/AluisioASG/nixexprs/blob/4b5399b1f065b1ba2703e84ac96827ab9b47c5e7/lib/attrsets.nix#L37-L42.

## Input
```nix
{
  /* Construct a binary search path (such as $PATH) containing the
     binaries for a set of packages.
     Example:
       makeBinPath ["/root" "/usr" "/usr/local"]
       => "/root/bin:/usr/bin:/usr/local/bin"
  */
  makeBinPath = makeSearchPathOutput "bin" "bin";

  /* concatMapAttrsToList :: (string -> any -> [any]) -> set -> [any]
   *
   * Like mapAttrsToList, but allows multiple values to be returned
   * from the mapping function as a list.
   */
  concatMapAttrsToList = mapper: attrs: concatLists (mapAttrsToList mapper attrs);
}
```

## Output
```nix
{
  /* Construct a binary search path (such as $PATH) containing the
    binaries for a set of packages.
    Example:
    makeBinPath ["/root" "/usr" "/usr/local"]
    => "/root/bin:/usr/bin:/usr/local/bin"
  */
  makeBinPath = makeSearchPathOutput "bin" "bin";

  /* concatMapAttrsToList :: (string -> any -> [any]) -> set -> [any]
    *
    * Like mapAttrsToList, but allows multiple values to be returned
    * from the mapping function as a list.
  */
  concatMapAttrsToList = mapper: attrs: concatLists (mapAttrsToList mapper attrs);
}

```

## Desired output

Same as the input. Ideally text would be aligned to the text in the first line and not to the space preceding it, and decorations would be preserved, but I suspect both could be achieved by simple preserving relative indentation inside the comment.

**Comment by zimbatm** [comment]
@Rizary and I discussed this issue today. We will come back after doing some research on the best approach to take.
