### ISSUE TITLE
tabs are not preserved in string literals

### ISSUE THREAD

**Issue by kamronm** [nix-community/nixpkgs-fmt#251]
Tabs within strings are converted to two spaces. Similar code formatters like rubocop and Prettier preserve tabs within strings, making this behavior surprising.

I noticed this while running nixpkgs-fmt on a NixOS configuration file with rules for /etc/exports. The change doesn't affect the meaning of the file, but might for other file types (TSV?).

## Input
```nix
{
  simpleStringLiteral = "col	col";

  multilineStringLiteral = ''
    col	col	col
  '';
}
```

## Output
```nix
--- Input	
+++ Output	
@@ -1,7 +1,7 @@
 {
-  simpleStringLiteral = "col	col";
+  simpleStringLiteral = "col  col";
 
   multilineStringLiteral = ''
-    col	col	col
+    col  col  col
   '';
 }
```

## Desired output

```nix
{
  simpleStringLiteral = "col	col";

  multilineStringLiteral = ''
    col	col	col
  '';
}
```

**Comment by zimbatm** [comment]
The formatter should leave the tabs intact.

Note that Nix doesn't support indenting with tabs in general as multiline strings don't use them to calculate the start of the string. So any tabs will be reflected in the string.

**Comment by lilyball** [comment]
I just ran into this myself with version 1.2.0. I have a `substituteInPlace` command that's being corrupted because the hard tabs in the `--replace` flag are being replaced.

It's pretty easy to reproduce. Also `--explain` doesn't list any rule violations:

```console
> printf '{ foo = "bar\tbaz"; }\n' | nixpkgs-fmt
{ foo = "bar  baz"; }
> printf '{ foo = "bar\tbaz"; }\n' | nixpkgs-fmt --explain
{ foo = "bar	baz"; }
```
