### ISSUE TITLE
Add '--write' argument

### ISSUE THREAD

**Issue by andyrichardson** [nix-community/nixpkgs-fmt#252]
**Is your feature request related to a problem? Please describe.**
It would be great if formatting could optionally be written to files on execution.

Tools such as [prettier](https://github.com/prettier/prettier) and [eslint](https://github.com/eslint/eslint) take a `--write` or `--fix` argument to opt-in to writing to the file.

**Describe the solution you'd like**

When running the following command

```sh
fmt --write flake.nix
```

The formatted file content would be written to the file rather than outputted to the console.

**Describe alternatives you've considered**

Maybe add something to the readme to make it easy for users to have this functionality (less ideal).

Something like (not tested)

```sh
find nix | grep .nix | xargs -L 1 -I {} bash -c "fmt {} > {}"  
```

**Additional context**

N/A

**Comment by zimbatm** [comment]
This is already the default. Just use `nixpkgs-fmt flake.nix`

**Comment by andyrichardson** [comment]
Thanks @zimbatm - looks like I was using `fmt` rather than `nixpkgs-fmt`
