### ISSUE TITLE
Design the CLI

### ISSUE THREAD

**Issue by zimbatm** [nix-community/nixpkgs-fmt#36]
There are essentially two modes of operation for the CLI:

* on a buffer: takes a buffer in with some nix code, outputs a formatted nix code
* on a dir: scan all the nix files in a folder and format them. with options to ignore some folders like `.git`

**Comment by matklad** [comment]
The right crate to walk the tree, respecting gitignore, is https://docs.rs/walkdir

**Comment by zimbatm** [comment]
@domenkozar mentioned that he is using https://pre-commit.com/ to format code automatically.

The tree walking is almost orthogonal to the tool, it would be nice if we didn't have to re-implement it with all the features that come with it like glob white and black listing.

**Comment by matklad** [comment]
I consider this closed by #130. We have two modes of operation: format a file, or format a directory, using "common sense" ignore patterns. If you need to to format a directory using custom ignore patterns, you should use something like `fd` and `xargs`. We *could* add flags to control `ignore` behavior, but I think that would just make `--help` longer for relatively marginal benefit.
