### ISSUE TITLE
sample: text block is not formatted correctly

### ISSUE THREAD

**Issue by kalbasit** [nix-community/nixpkgs-fmt#42]
## Input
```nix
{ lib, ... }:

with lib;

{
  nix.extraOptions = ''
    builders-use-substitutes = true
  '';
}
```

## Output
```nix
{ lib, ... }:

with lib;

  {
    nix.extraOptions = ''
    builders-use-substitutes = true
  '';
  }

```

Expected

```
    nix.extraOptions = ''
    	builders-use-substitutes = true
  	'';
```

**Comment by zimbatm** [comment]
Thanks!

This is related to #20 

/cc @matklad

**Comment by matklad** [comment]
Thanks! That's an interesting example, because in this case, we need to change not the whitespace, but the contents of the string literal, in a semantic-preserving way.

**Comment by matklad** [comment]
Closed by https://github.com/nix-community/nixpkgs-fmt/pull/57
