### ISSUE TITLE
Haskell comma in function parameters

### ISSUE THREAD

**Issue by matklad** [nix-community/nixpkgs-fmt#46]
I see two different patterns which are used to format function arguments:

1. Haskell comma:

```
{ pkgs ? import ./nix/nixpkgs.nix {}
, src ? builtins.fetchGit {
    url = ./.;
    ref = "HEAD";
  }
}:
pkgs.example rec {}
```

2. More traditional, with comma after the pattern:

```
  toINI = {
    mkSectionName ? (name: libStr.escape [ "[" "]" ] name),
    mkKeyValue    ? mkKeyValueDefault {} "="
  }: attrsOfAttrs:
    let ...
```

which one we should use?

Additionally, is it a good idea to to keep first parameter on the same line, as in `{ pkgs ? import ./nix/nixpkgs.nix {}` ?

**Comment by Mic92** [comment]
I don't see many examples where this would actually have an effect in nixpkgs at the moment. For consistency/readability I would probably would vote for the haskell comma.

**Comment by matklad** [comment]
> I would also keep the first parameter on the first line, since the comma will align the other lines with the { in the first line. It is a bit more compact since one line is saved.

The problem with this is that we'll need to indent the rest of the prameters. Consider the second example with haskell-comma style:

```
  toINI = {
    mkSectionName ? (name: libStr.escape [ "[" "]" ] name)
  , mkKeyValue    ? mkKeyValueDefault {} "="
  }: attrsOfAttrs:
    let ...
```

vs

```
  toINI = { mkSectionName ? (name: libStr.escape [ "[" "]" ] name)
          , mkKeyValue    ? mkKeyValueDefault {} "="
          }: attrsOfAttrs:
            let ...
```

**Comment by Mic92** [comment]
> The problem with this is that we'll need to indent the rest of the prameters. Consider the second example with haskell-comma style:

Fair point. Less indentation is probably better.

**Comment by zimbatm** [comment]
Most of nixpkgs is using the comma-first notation, but also has top-level functions so the indent is not an issue.

In general I would prefer if the indent was only changing of +- 2 between each line. I find this more regular but don't have a strong argument otherwise.
