### ISSUE TITLE
URLs and paths

### ISSUE THREAD

**Issue by matklad** [nix-community/nixpkgs-fmt#61]
We should rewrite URLs like `http://example.com` to string `"http://example.com"`

Should we do the same for paths like `./some/dir`? Or are paths and urls are completely different things?  `rnix` uses `TOKEN_PATH` for both of these, and I wonder if that should be fixed.

**Comment by zimbatm** [comment]
Let's hold on on this-one until the RFC is resolved: https://github.com/NixOS/rfcs/pull/45

**Comment by zimbatm** [comment]
The issue with URLs is that they are just another form of string literal.

Path literals are actually creating new paths so they don't suffer from the same issue.

**Comment by matklad** [comment]
Ok, let's close this then until the RFC moves forward. 

I've opened https://gitlab.com/jD91mZM2/rnix/issues/12 for fixing rnix
