### ISSUE TITLE
Build failure on Darwin

### ISSUE THREAD

**Issue by smaret** [nix-community/nixpkgs-fmt#7]
On Darwin "cargo build" fails with the following error message:

```
  = note: ld: framework not found Security
          clang-7: error: linker command failed with exit code 1 (use -v to see invocation)
```

I think that `darwin.apple_sdk.frameworks.Security` should be added to the `buildInputs`.

**Comment by matklad** [comment]
Do you know *why* we need `darwin.apple_sdk.frameworks.Security` in the first place? This seems strange, we shoudn't be doing any non-trivial interaction with OS at all

**Comment by smaret** [comment]
I have no idea. I've put the full build log [here](https://gist.github.com/smaret/516f6c6f6d09f625692b19fe81b43523).

**Comment by amitu** [comment]
I am getting similar error message, 

```shell
  = note: ld: framework not found Security
          clang-7: error: linker command failed with exit code 1 (use -v to see invocation)
```

Even though I have framework added:

```nix
    buildInputs = [ rust ] ++ (
       stdenv.lib.optionals stdenv.isDarwin [
         frameworks.Security
         frameworks.CoreServices
         frameworks.CoreFoundation
         frameworks.Foundation
         frameworks.AppKit
       ]
    );
```

It used to work for me on Catalina, and stopped working on Big Sur.

**Comment by zimbatm** [comment]
@amitu are you building nixpkgs-fmt on Big Sur, or another project?

**Comment by amitu** [comment]
This is not related to `nixpkgs-fmt` (which builds fine in Big Sur).

**Comment by jaredramirez** [comment]
@amitu Did you figure this out? I'm hitting the same error (also on another project, not on nixpkgs-fmt)

**Comment by amitu** [comment]
@jaredramirez, unfortunately, no :-(. What's weird is my colleague has exact same setup, and it works on his machine. Also, it works on M1 machines. 

If you figure it out let me know :-)

**Comment by michaeljohnclancy** [comment]
Hey any success over here? Running into the same issue even if I add the framework as a nativeBuildInput
