### ISSUE TITLE
sample: function argument comments

### ISSUE THREAD

**Issue by zimbatm** [nix-community/nixpkgs-fmt#71]
src/rules.rs `apply_arg` should probably also look if the node is a comment:

## Input
```nix
{
  foo =
    # describe bar
    bar:
    # describe baz
    baz:
      fnbody;
}
```

## Output
```nix
{
  foo =
  # describe bar
      bar:
      # describe baz
          baz:
            fnbody;
}

```

## Desired output

See input

**Comment by zimbatm** [comment]
thinking about this a bit more, I think that comments need to be aligned to the *next* element indent in a 3rd phase. And then the indent phase should skip over comments for all the rules.

**Comment by matklad** [comment]
Does `nix` has some sort of doc-comments? The ideal way to treat doc comments is to just attach them the following value, such that the syntax tree is

```
LAMBDA
  PARAMETER
    COMMENT
    PATTERN
```

and not


```
LAMBDA
  COMMENT
  PARAMETER
    PATTERN
```

perhaps we should just even attach all like comments to following values, unless there's a blank line in-between?

**Comment by zimbatm** [comment]
I wish :) there is no such thing as a doc-comment except maybe by convention.

Comments don't influence the indent, that's why I was thinking they might be handled in a different phase.

**Comment by matklad** [comment]
I am looking at the Kotlin's formatter, and looks like they handle this by *negative* rules. That is, a typical indent rule is "indent everything except for X, Y, and Z", and I think we should do this as well. 

https://github.com/JetBrains/kotlin/blob/7d173ed3856e429739b55d8c3892e1b85ca41571/idea/formatter/src/org/jetbrains/kotlin/idea/formatter/KotlinCommonBlock.kt#L682-L690

Also, debug names for rules look nice!
