### ISSUE TITLE
Debug mode

### ISSUE THREAD

**Issue by zimbatm** [nix-community/nixpkgs-fmt#74]
It would be cool if the engine could should all the matching rules with the diff. The more rule we add, the harder it becomes to understand how they interact with each-other.

Example output:
```
<rule name> matched <element>
<diff>
```

What do you think @matklad ?

**Comment by matklad** [comment]
Yeah, I also find it quite hard to debug interactions between the rules. Though, I am not sure if just somehow showing matching rules would help: it seems like it would produce way to much information to be useful. 

At the moment, I just comment out some rules to minimize the example. I imagine that could be automated: formatting could print a series of diffs, starting with "zero rules applied", and ending with "all rules applied". Still not sure if that would be more effective than just manually commenting out specifc things

**Comment by zimbatm** [comment]
The difference would mainly be that as a user it would be possible to understand what is going on without toughing the code (assuming that the output is helpful). I think rules would also have to have names attached to them so they could be distinguished one from another.

Brainstorming a bit more, another approach might be to attach some assertions onto a node, asserting that rule X is going to be applied to it.

**Comment by matklad** [comment]
This is implemented as `--explain` flag in #79!
