### ISSUE TITLE
NUR package?

### ISSUE THREAD

**Issue by Mic92** [nix-community/nixpkgs-fmt#82]
I currently have added it to my namespace:

```
$ nix-shell -p nur.repos.mic92.nixpkgs-fmt
$ nixpkgs-fmt --help
nixpkgs-fmt 0.1
Format Nix code

USAGE:
    nixpkgs-fmt [FLAGS] [OPTIONS] [FILE]

FLAGS:
    -h, --help        Prints help information
    -i, --in-place    Overwrite FILE in place
        --parse       Show syntax tree instead of reformatting
    -V, --version     Prints version information

OPTIONS:
    -o, --output <file>    Place the output into <file>

ARGS:
    <FILE>    File to reformat
```

However it might be useful to have it might useful to have it a namespace
managed by one of the maintainers. Otherwise you can always make a pull request to my repository ...

**Comment by Mic92** [comment]
I already find it in the current state quite useful.

**Comment by Mic92** [comment]
Also makes it easier to test.

**Comment by zimbatm** [comment]
Go for it. My plan was to cut a release and package it in nixpkgs directly but having a NUR overlay wouldn't hurt.
