### ISSUE TITLE
multi-line string is indented wrong in paranthese

### ISSUE THREAD

**Issue by Mic92** [nix-community/nixpkgs-fmt#83]
```
(let
  a = ''
    foo
  '';
 in a)
```

results in

```
(
  let
    a = ''
      foo
      '';
  in
    a
)
```

instead of

```
(
  let
    a = ''
      foo
    '';
  in
    a
)
```

a more practical example would be:

```
wpa_supplicant.overrideAttrs(old: {
  postBuild = ''
    echo foo
  '';
})
```

->

```
wpa_supplicant.overrideAttrs (
  old: {
    postBuild = ''
      echo foo
      '';
  }
)
```

**Comment by matklad** [comment]
This is sort-of intentional, to make formatting with `''` on the same and the next line look similarly:

```nix
postBuild = 
  ''
  echo foo
  '';
```

vs

```nix
postBuild = ''
  echo foo
  '';
```


and it also seem to match better indented semi which we also use:

```
postBuild = 
  ''echo foo''
  ;
```

It does differ from arrays though:

```
postBuild = [
    92
];
```

@zimbatm what should we do here?

**Comment by Mic92** [comment]
The result is different though if you skip the parentheses:

```
let
  a = ''
    foo
  '';
 in a
```

**Comment by zimbatm** [comment]
@matklad for consistency's sake I believe that the `''` should be balanced the same way as for the arrays and attribute sets. And the inner text be indented one more just like the inner elements of the array.
