### ISSUE TITLE
RuntimeError: unreachable executed

### ISSUE THREAD

**Issue by zimbatm** [nix-community/nixpkgs-fmt#93]
**Describe the bug**

Formatting this code produces a runtime error:
```
{ } =
```

**To Reproduce**

1. Run `echo "{} =" > sample.nix`
2. Run `nixpkgs-fmt ./sample.nix'
```
thread 'main' panicked at 'assertion failed: prev.is_none()', src/engine/fmt_model.rs:267:9
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Expected behavior**
No runtime error

**System information**

nixpkgs-fmt version: master 81e23412987e762b7b9361733b5e862ce238eee7

**Comment by matklad** [comment]
closed by #96
