### ISSUE TITLE
slight formatting issue: brace is left alone in args

### ISSUE THREAD

**Issue by layus** [nix-community/nixpkgs-fmt#94]
## Input
```nix
{foo,
bar}:
              foo+bar
```

## Output
```nix
{
  foo
, bar
}:
foo + bar

```

## Desired output

This seems more canonical in nixpkgs:

```nix
{ foo
, bar
}:
foo + bar
```

**Comment by matklad** [comment]
This is sort of intentional, see https://github.com/nix-community/nixpkgs-fmt/issues/46.

The problem with placing first parameter after `{` is that it forces parameters to align to `{`, which doesn't work to well in cases like this:

```
{
  f = { x
      , y 
      }: body
}
```

**Comment by layus** [comment]
Fair point indeed.

That being said, top-level functions are a bit different and could be handled differently, because this example looks like an unfinished tetris game. The curly bracket is itching to fall one square below ;-).

But this has already been discussed, so closing for now.

```nix
{ 
  foo
, bar
, baz
}:
foo + bar
```

# Okay examples

```nix
{
  foo,
  bar,
  baz
}:
foo + bar
```

```nix
{ foo
, bar
, baz
}:
foo + bar
```

```nix
{
  f = { x
      , y
      , z
      }: body;
}
```

```nix
{
  f = { 
    x,
    y,
    z,
  }: body;
}
```

## Not okay examples

```nix
{ 
  foo
, bar
, baz
}:
foo + bar
```

```nix
{
  f = { 
    x
  , y
  , z
  }: body;
}
```

**Comment by zimbatm** [comment]
don't give up @layus ! the format is definitely up for discussion

**Comment by zimbatm** [comment]
This is the hardest problem we've had with the nix format, making it work in the top-level and deeper levels. We haven't found a solution that keep the rules simple.

I guess an alternative would be to force the deeper level to be on multiple lines like that:
```nix
{
  f =
    { x
    , y
    , z
    }: body;
}
```

**Comment by layus** [comment]
> I guess an alternative would be to force the deeper level to be on multiple lines like that:
> 
> ```nix
> {
>   f =
>     { x
>     , y
>     , z
>     }: body;
> }
> ```

That's definitely an option, and it looks quite nice to me. Especially given that nested functions that receive an attrset as argument do not look too frequent in nixpkgs.

**Comment by layus** [comment]
Function parameters are hard, because they have no opening and closing symbols. We could use `λ a: b: c: 1` for the sake of reasoning. then an argument list is just like a normal list. See the simmilarity between these two ?

```nix
{
  f = λ
    { x, y, z}:
	foo:
    { a, b, c}:
	bar:
	  body;
}
```

```nix
{
  f = [
    { x, y, z}
	foo
    { a, b, c}
	bar
  ];
}
```

So either the arguments are on the same line, or they are on separate lines, with a leading newline. That rule is easy to state, and somewhat alleviates our current issue.

Fully expanded ;-):

```nix
{
  f = λ
    { x
    , y
    , z}:
	foo:
    { a
    , b
    , c}:
	bar:
	  body;
}
```

**Comment by zimbatm** [comment]
Why are `foo:` and `bar:` indented once more in your example? The array argument should dictate that all the function arguments would be aligned on the same indent?

**Comment by layus** [comment]
they say a figure is better than a thousand words ;-), so here it comes:

```nix
{
  f =
    set1:
    foo:
    set2:
    bar:
	  body;
}
```

```nix
{
  f =
    {
      x,
      y,
      z
    }:
    foo:
    { 
      a,
      b,
      c
    }:
    bar:
	  body;
}
```

**Comment by layus** [comment]
> Why are `foo:` and `bar:` indented once more in your example? The array argument should dictate that all the function arguments would be aligned on the same indent?

They are not. Could it be a tab vs spaces issue ? I edited my previous comment to fix that.

**Comment by zimbatm** [comment]
Okay that makes more sense now with the indent fixed :)

I think the body will have to be on the same level as the argument to avoid too much movement:

single-line:
```nix
{
  f = a: b: c:
    body;
}
```

multi-line:
```nix
{
  f =
    a:
    b:
    c:
    body;
}
```

If the body is really large it will create a lot of whitespace diff otherwise.

**Comment by zimbatm** [comment]
And if that's applied then we can keep the comma-first notation for the function arguments. This notation is quite pervasive in nixpkgs:
```nix
{ foo
, bar
, baz
}:
```

**Comment by domenkozar** [comment]
What we do in canonix is to format top-level differently than inline.
